name: depoly-iot-backend

on:
  push:
    branches:
      - main
    paths:
      - 'iot-backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - run: cd iot-backend && docker build -t livfarm/iot-backend .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}} 
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}} 
      - run: docker push livfarm/iot-backend
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save livfarm
      - run: kubectl rollout restart deployment iot-backend-depl
