name: depoly-landing-page

on:
  push:
    branches:
      - main
    paths:
      - 'landing-page/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - run: cd landing-page && docker build -t livfarm/landing-page .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}} 
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}} 
      - run: docker push livfarm/landing-page
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save livfarm
      - run: kubectl rollout restart deployment landing-page-depl
