name: tests-iot-backend
# if add new file, it can execute the tests as parallel
on:
  pull_request:
    paths:
      - 'iot-backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd iot-backend && npm i && npm run test